[project]
name = "langgraph-course"
version = "0.1.0"
description = ""
authors = [
    {name = "pulkit-yadav-aptos-com",email = "pulkit.yadav@aptos.com"}
]
requires-python = ">=3.11,<4.0.0"
dependencies = [
    "langchain (>=1.2.17,<2.0.0)",
    "langchain-ollama (>=1.1.0,<2.0.0)",
    "langchain-tavily (>=0.2.18,<0.3.0)",
    "langgraph (>=1.1.10,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
